In [64]:
import numpy as np
print("numpy Version:", np.__version__)

numpy Version: 2.3.5


## 1.1 creating numpy arrays

In [65]:
temperatures = np.array([36.6,37.1,36.9,38.2,37.0])
print("shape:", temperatures.shape)
print("Data types:", temperatures.dtype)
print("Dimensions:", temperatures.ndim)

shape: (5,)
Data types: float64
Dimensions: 1


## 2 dimensional array has a row and a column
### Each row contains a student's test score in Maths, English, and Science

In [66]:
scores_list = [[85, 90, 78], 
               [92, 88, 95], 
               [70, 75, 80], 
               [88, 82, 91]]
scores = np.array(scores_list)

print("Shape:", scores.shape)
print("Data types:", scores.dtype)
print("Dimensions:", scores.ndim)

Shape: (4, 3)
Data types: int64
Dimensions: 2


In [67]:
#creating an array

hours = np.arange(0, 24)
print(hours.shape)

(24,)


In [68]:
#creating an array with steps

time = np.arange(0, 24, 5)
print(time)
print(time.shape)

[ 0  5 10 15 20]
(5,)


In [69]:
#10 equally spaced events
percentages = np.linspace(11, 40, 5)
print(percentages)

[11.   18.25 25.5  32.75 40.  ]


In [70]:
#Arrays of zeros and ones
zeros = np.zeros(4)
print(zeros)

[0. 0. 0. 0.]


In [71]:
# two-dimensional
zeros = np.zeros((3,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [72]:
ones = np.ones(7)
print(ones)

[1. 1. 1. 1. 1. 1. 1.]


In [73]:
#2-dimensional
ones = np.ones((4,6))
print(ones)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


## 1.2 Indexing and Slicing

In [74]:
#Indexing is that we want a particular item from our dataset (simple values)
#slicing means we want a group of items...(multiple values)

temperatures = np.array([36.6,37.1,36.9,38.2,37.0])
print("First Temperature:", temperatures[0])
print("Last Temperature:", temperatures [-1])
print("First three readings:", temperatures[0:3])  # this can also be done using [:3])
print("Last three readings:", temperatures [-3:])

#Boolean indexing
fever_threshold = 37.5
fevers = temperatures [temperatures > fever_threshold]
print("fevers_readings(>37.5)", fevers)


First Temperature: 36.6
Last Temperature: 37.0
First three readings: [36.6 37.1 36.9]
Last three readings: [36.9 38.2 37. ]
fevers_readings(>37.5) [38.2]


In [75]:
# Column labels: [Maths, English, Science]
scores_list = [[85, 90, 78], 
               [92, 88, 95], 
               [70, 75, 80], 
               [88, 82, 91]]
scores = np.array(scores_list)

print("Student 1's Scores:", scores[0]) # or
scores_list[0]

Student 1's Scores: [85 90 78]


[85, 90, 78]

In [76]:
#Maths score for everyone (To get a particular column, you separate with a (:) and a comma(,)). The comma separates rows from columns
#In numpy
print("All Math Scores:", scores[:,0])


All Math Scores: [85 92 70 88]


In [77]:
# In Python
math_score = []
for i in scores_list:
    math_score.append(i[0])
    
print(math_score) 

[85, 92, 70, 88]


## 1.3 Vectorized Operation

In [78]:
# creating vectors (vectors are important in numpy because it makes it easier to carry out bulk operations)

import time
import numpy as np  # Added missing numpy import

big_list = list(range(1_000_000))
big_array = np.arange(0, 1_000_001)

#in Python loop
start = time.time()
squared_list = [x**2 for x in big_list]
python_time = time.time() - start

#Numpy vectorized
start = time.time()
squared_array = big_array**2
numpy_time = time.time() - start

print(f"Python Time: {python_time:.4f} seconds")
print(f"Numpy Time: {numpy_time:.4f} seconds")
python_time/numpy_time

Python Time: 0.0520 seconds
Numpy Time: 0.0019 seconds


27.169825436408978

In [79]:
add_scores = scores /10
print(scores)
print(add_scores)

[[85 90 78]
 [92 88 95]
 [70 75 80]
 [88 82 91]]
[[8.5 9.  7.8]
 [9.2 8.8 9.5]
 [7.  7.5 8. ]
 [8.8 8.2 9.1]]


## 1.4 Aggregation functions
##### axis = 0 Operate down the rows(collapse the rows, keep the columns)(top to bottom)
##### axis = 1 Operate down the columns and keep the rows)(left to right)

In [84]:
# With this function, you can count data, sum data, etc
print("Score per subject", np.sum(scores, axis = 0))
print ("Score per person", np.sum (scores, axis = 1))

print("Average score per subject", np.average(scores, axis = 0))
print("Average score per person", np.average(scores, axis = 1))

print ("Minimum score per subject", np. min(scores, axis = 0))
print ("Minimum score per person", np. min(scores, axis = 1))
print ("Maximum score per subject", np. max(scores, axis = 0))
print ("Maximum score per person", np. max(scores, axis = 1))
       

Score per subject [335 335 344]
Score per person [253 275 225 261]
Average score per subject [83.75 83.75 86.  ]
Average score per person [84.33333333 91.66666667 75.         87.        ]
Minimum score per subject [70 75 78]
Minimum score per person [78 88 70 82]
Maximum score per subject [92 90 95]
Maximum score per person [90 95 80 91]


## 1.5 Reshaping arrays

In [94]:
print (temperatures.shape)
temp_reshaped = temperatures.reshape(5,1)
temp_reshaped.shape

print (scores.shape)
score_shaped = scores.reshape(-1,2)
print(score_shaped.shape)

(5,)
(4, 3)
(6, 2)
